-- Persist post publish feed generation work so failures can be retried.
-- Flyway manages the transaction boundary for this migration.

CREATE TABLE feed_generation_jobs (
    job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    modified_at TIMESTAMP(6) NOT NULL,
    post_id BIGINT NOT NULL,
    board_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    processing_started_at TIMESTAMP(6),
    completed_at TIMESTAMP(6),
    last_error_message VARCHAR(500),
    CONSTRAINT uk_feed_generation_jobs_post UNIQUE (post_id),
    CONSTRAINT ck_feed_generation_jobs_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_feed_generation_jobs_retry_count CHECK (retry_count >= 0)
);

CREATE INDEX idx_feed_generation_jobs_status_created
    ON feed_generation_jobs (status, created_at, job_id);

CREATE INDEX idx_feed_generation_jobs_processing
    ON feed_generation_jobs (status, processing_started_at);
