-- Baseline schema generated from current Hibernate metadata for PostgreSQL.
-- Existing non-empty databases must be baselined at version 1 before applying later migrations.

create table ad_click_logs (log_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, anonymous_reason varchar(40), clicked_at timestamp(6) not null, ip_address varchar(45), ad_id bigint not null, user_id bigint, primary key (log_id));

create table admins (admin_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, is_active varchar(1) not null check (is_active in ('N','Y','N')), role varchar(50) not null, board_id bigint not null, user_id bigint not null, primary key (admin_id));

create table ads (ad_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, ad_name varchar(100) not null, click_count integer not null, end_date timestamp(6), image_url varchar(255) not null, impression_count integer not null, is_active varchar(1) not null check (is_active in ('N','Y','N')), placement varchar(100) not null, start_date timestamp(6) not null, target_url varchar(255) not null, primary key (ad_id));

create table agent_activity_logs (log_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, action_type varchar(30) not null, request_ip varchar(45), request_path varchar(255), target_id bigint, target_type varchar(20), agent_id bigint not null, user_id bigint, primary key (log_id));

create table agent_daily_quotas (agent_daily_quota_id bigint generated by default as identity, action_type varchar(20) not null, quota_date date not null, used_count bigint not null, agent_id bigint not null, primary key (agent_daily_quota_id), constraint uk_agent_daily_quotas_agent_date_action unique (agent_id, quota_date, action_type));

create table agents (agent_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, agent_token_hash varchar(255) not null unique, claimed_at timestamp(6), description TEXT not null, is_deleted varchar(1) not null check (is_deleted in ('N','Y','N')), last_used_at timestamp(6), name varchar(100) not null, status varchar(20) not null, user_id bigint, primary key (agent_id));

create table board_ai_info (board_id bigint not null, created_at timestamp(6) not null, modified_at timestamp(6) not null, guide_prompt TEXT, primary key (board_id));

create table board_categories (category_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, is_active varchar(1) not null check (is_active in ('N','Y','N')), is_default varchar(1) check (is_default in ('N','Y','N')), min_write_role varchar(20), name varchar(100) not null, sort_order integer not null, board_id bigint not null, primary key (category_id));

create table board_subscriptions (board_id bigint not null, user_id bigint not null, created_at timestamp(6) not null, modified_at timestamp(6) not null, role varchar(20) not null, sort_order integer not null, primary key (board_id, user_id), constraint uk_board_subscriptions_user_sort_order unique (user_id, sort_order));

create table boards (board_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, agent_use_yn varchar(1) default 'N' check (agent_use_yn in ('N','Y','N')), allow_nsfw varchar(1) not null check (allow_nsfw in ('N','Y','N')), board_name varchar(100) not null, board_url varchar(100) not null, description varchar(255), icon_url varchar(255), is_active varchar(1) not null check (is_active in ('N','Y','N')), is_public varchar(1) default 'Y' not null check (is_public in ('N','Y','N')), sort_order integer not null, creator_id bigint not null, primary key (board_id), constraint uk_boards_board_name unique (board_name), constraint uk_boards_board_url unique (board_url));

create table comment_closures (created_at timestamp(6) not null, depth integer not null, modified_at timestamp(6) not null, ancestor_id bigint not null, descendant_id bigint not null, primary key (ancestor_id, descendant_id));

create table comment_likes (comment_id bigint not null, user_id bigint not null, created_at timestamp(6) not null, modified_at timestamp(6) not null, primary key (comment_id, user_id));

create table comment_versions (history_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, original_content TEXT, version_type varchar(50) not null, comment_id bigint not null, modifier_id bigint not null, primary key (history_id));

create table comments (comment_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, content TEXT not null, depth integer not null, is_deleted varchar(1) not null check (is_deleted in ('N','Y','N')), like_count integer not null, agent_id bigint, parent_id bigint, post_id bigint not null, user_id bigint not null, primary key (comment_id));

create table common_code_details (id bigint generated by default as identity, code_name varchar(100) not null, code_value varchar(100) not null, created_at timestamp(6) not null, is_active varchar(1) not null check (is_active in ('N','Y','N')), modified_at timestamp(6) not null, sort_order integer not null, type_code varchar(50) not null, primary key (id), constraint uk_code_details_value unique (type_code, code_value));

create table common_codes (type_code varchar(50) not null, created_at timestamp(6) not null, description varchar(255), modified_at timestamp(6) not null, type_name varchar(100) not null, primary key (type_code));

create table display_name_histories (history_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, changed_at timestamp(6) not null, new_name varchar(50) not null, previous_name varchar(50) not null, user_id bigint not null, primary key (history_id));

create table draft_posts (draft_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, contents TEXT, file_ids_json TEXT, is_notice boolean not null, is_nsfw boolean not null, is_secret boolean not null, is_spoiler boolean not null, tags_json TEXT, title varchar(200), board_id bigint not null, category_id bigint, original_post_id bigint, user_id bigint not null, primary key (draft_id));

create table emoticon_images (image_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, image_url varchar(500) not null, sort_order integer not null, emoticon_id bigint, primary key (image_id));

create table emoticon_masters (emoticon_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, is_active varchar(1) not null, name varchar(100) not null, purchase_count integer not null, tags text[], thumbnail_url varchar(500), creator_id bigint, primary key (emoticon_id));

create table emoticon_purchases (purchase_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, purchased_price integer not null, emoticon_id bigint not null, user_id bigint not null, primary key (purchase_id), constraint uk_emoticon_purchases_user_emoticon unique (user_id, emoticon_id));

create table error_logs (error_log_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, error_code varchar(20), error_type varchar(100) not null, http_status integer not null, ip_address varchar(45) not null, is_resolved varchar(1) not null, message varchar(500) not null, request_method varchar(10) not null, request_uri varchar(500) not null, resolved_at timestamp(6), resolved_by bigint, resolved_memo varchar(500), stack_trace TEXT, user_agent varchar(500), user_id bigint, primary key (error_log_id));

create table files (file_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, delete_last_error varchar(1000), delete_requested_at timestamp(6), delete_retry_count integer not null, file_path varchar(255) not null, file_size bigint not null, mime_type varchar(100) not null, original_name varchar(255) not null, related_id bigint, related_type varchar(50), storage_status varchar(30) not null check (storage_status in ('ACTIVE','PENDING_DELETE','DELETING','DELETE_FAILED')), uploader_id bigint not null, primary key (file_id));

create table global_configs (config_key varchar(100) not null, created_at timestamp(6) not null, modified_at timestamp(6) not null, config_value varchar(255), description varchar(255), primary key (config_key));

create table ip_blocks (ip_address varchar(45) not null, created_at timestamp(6) not null, modified_at timestamp(6) not null, end_date timestamp(6), reason varchar(255), start_date timestamp(6) not null, admin_id bigint not null, primary key (ip_address));

create table login_histories (history_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, failure_reason varchar(50), ip_address varchar(45) not null, is_success varchar(1) not null check (is_success in ('N','Y','N')), login_id varchar(30) not null, user_agent varchar(500), user_id bigint, primary key (history_id));

create table logs (log_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, action_type varchar(100) not null, details TEXT, ip_address varchar(45) not null, user_id bigint, primary key (log_id));

create table message_queue (queue_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, content TEXT not null, delivery_method varchar(20) not null, delivery_uncertain_at timestamp(6), processing_started_at timestamp(6), requested_at timestamp(6) not null, retry_count integer not null, send_attempt_confirmed_at timestamp(6), send_attempt_id varchar(64), send_attempt_started_at timestamp(6), status varchar(50) not null, target_user_id bigint not null, primary key (queue_id));

create table messages (message_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, content TEXT not null, is_deleted_by_receiver varchar(1) not null check (is_deleted_by_receiver in ('N','Y','N')), is_deleted_by_sender varchar(1) not null check (is_deleted_by_sender in ('N','Y','N')), is_read varchar(1) not null check (is_read in ('N','Y','N')), receiver_id bigint not null, sender_id bigint not null, primary key (message_id));

create table notifications (notification_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, content varchar(255) not null, is_read varchar(1) not null check (is_read in ('N','Y','N')), notification_type varchar(50) not null, source_id bigint, source_type varchar(50) not null, actor_id bigint, actor_agent_id bigint, user_id bigint not null, primary key (notification_id));

create table password_histories (history_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, password_hash varchar(255) not null, user_id bigint not null, primary key (history_id));

create table password_reset_tokens (token_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, delivery_status varchar(20), expiry_date timestamp(6) not null, is_used varchar(1) not null check (is_used in ('N','Y','N')), token varchar(64) not null unique, user_id bigint not null, primary key (token_id));

create table point_histories (history_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, amount integer not null, balance_after integer not null, description varchar(255), related_id bigint, related_type varchar(50), type varchar(50) not null, user_id bigint not null, primary key (history_id));

create table popular_posts (cache_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, rank integer not null, ranking_type varchar(50) not null, score float(53) not null, post_id bigint not null, primary key (cache_id));

create table post_likes (post_id bigint not null, user_id bigint not null, created_at timestamp(6) not null, modified_at timestamp(6) not null, primary key (post_id, user_id));

create table post_tags (post_id bigint not null, tag_id bigint not null, created_at timestamp(6) not null, modified_at timestamp(6) not null, primary key (post_id, tag_id));

create table post_versions (history_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, original_contents TEXT, original_title varchar(200), version_type varchar(50) not null, modifier_id bigint not null, post_id bigint not null, primary key (history_id));

create table posts (post_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, comment_count integer not null, contents TEXT not null, is_deleted varchar(1) not null check (is_deleted in ('N','Y','N')), is_notice varchar(1) not null check (is_notice in ('N','Y','N')), is_nsfw varchar(1) not null check (is_nsfw in ('N','Y','N')), is_secret varchar(1) default 'N' not null check (is_secret in ('N','Y','N')), is_spoiler varchar(1) not null check (is_spoiler in ('N','Y','N')), like_count integer not null, title varchar(200) not null, view_count integer not null, agent_id bigint, board_id bigint not null, category_id bigint, user_id bigint not null, primary key (post_id));

create table purchase_history (purchase_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, purchased_price integer not null, item_id bigint not null, user_id bigint not null, primary key (purchase_id));

create table refresh_tokens (token_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, device_info varchar(255), expires_at timestamp(6) not null, ip_address varchar(45) not null, is_revoked varchar(1) not null check (is_revoked in ('N','Y','N')), token_hash varchar(255) not null unique, user_id bigint not null, primary key (token_id));

create table reports (report_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, contents TEXT, processed_remark varchar(255), processor_user_id bigint, reason_type varchar(50) not null, remark varchar(255), status varchar(50) not null, target_id bigint not null, target_type varchar(50) not null, admin_id bigint, reporter_id bigint not null, primary key (report_id), constraint uk_reports_user_target unique (reporter_id, target_type, target_id));

create table sanctions (sanction_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, content_id bigint, content_type varchar(50), end_date timestamp(6), remark varchar(255), start_date timestamp(6) not null, type varchar(50) not null, admin_id bigint not null, target_user_id bigint not null, primary key (sanction_id));

create table scraps (post_id bigint not null, user_id bigint not null, created_at timestamp(6) not null, modified_at timestamp(6) not null, remark varchar(255), primary key (post_id, user_id));

create table search_personalization (log_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, keyword varchar(255) not null, normalized_keyword varchar(255) not null, searched_at timestamp(6) not null, user_id bigint not null, primary key (log_id), constraint uk_search_personalization_user_normalized_keyword unique (user_id, normalized_keyword));

create table search_statistics (id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, keyword varchar(255) not null, search_count integer not null, search_date date not null, primary key (id), constraint uk_search_statistics_keyword_date unique (keyword, search_date));

create table shop_items (item_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, description varchar(255), image_url varchar(255), is_active varchar(1) not null check (is_active in ('N','Y','N')), item_name varchar(100) not null, item_type varchar(50) not null, price integer not null, target_id bigint, primary key (item_id));

create table social_accounts (social_account_id bigint generated by default as identity, provider varchar(255) not null, provider_id varchar(255) not null, user_id bigint not null, primary key (social_account_id), constraint uk_social_accounts_provider_provider_id unique (provider, provider_id), constraint uk_social_accounts_user_provider unique (user_id, provider));

create table tags (tag_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, post_count integer not null, tag_name varchar(100) not null unique, primary key (tag_id));

create table user_blocks (relation_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, target_id bigint not null, user_id bigint not null, primary key (relation_id), constraint uk_user_blocks unique (user_id, target_id));

create table user_feeds (feed_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, content_id bigint not null, content_type varchar(50) not null, criteria_id bigint, feed_type varchar(50) not null, is_read varchar(1) not null check (is_read in ('N','Y','N')), source_criteria varchar(50) not null, target_user_id bigint not null, primary key (feed_id), constraint uk_user_feeds_target_content_source unique (target_user_id, feed_type, content_type, content_id, source_criteria, criteria_id));

create table user_notification_settings (notification_type varchar(50) not null check (notification_type in ('LIKE','COMMENT','REPLY')), user_id bigint not null, created_at timestamp(6) not null, modified_at timestamp(6) not null, is_enabled varchar(1) not null check (is_enabled in ('N','Y','N')), primary key (notification_type, user_id));

create table user_points (user_id bigint not null, created_at timestamp(6) not null, modified_at timestamp(6) not null, current_point integer not null, primary key (user_id));

create table user_settings (user_id bigint not null, created_at timestamp(6) not null, modified_at timestamp(6) not null, hide_nsfw varchar(1) not null check (hide_nsfw in ('N','Y','N')), language varchar(10) not null, theme varchar(20) not null, timezone varchar(50) not null, primary key (user_id));

create table users (user_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, deleted_at timestamp(6), display_name varchar(50) not null, email varchar(100) not null unique, is_email_verified varchar(1) not null check (is_email_verified in ('N','Y','N')), is_super_admin varchar(1) default 'N' not null check (is_super_admin in ('N','Y','N')), last_login_at timestamp(6), login_id varchar(30) not null unique, password varchar(255) not null, profile_image_url varchar(255), status varchar(20) not null, primary key (user_id));

create table verification_codes (verification_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, code varchar(64) not null, delivery_status varchar(20), email varchar(100) not null, expiry_date timestamp(6) not null, is_ticket_consumed varchar(1) not null check (is_ticket_consumed in ('N','Y','N')), is_verified varchar(1) not null check (is_verified in ('N','Y','N')), purpose varchar(30) not null check (purpose in ('SIGNUP','FIND_ID','PASSWORD_RESET','CHANGE_EMAIL')), ticket_expiry_date timestamp(6), verification_ticket varchar(64), primary key (verification_id));

create table view_histories (view_history_id bigint generated by default as identity, created_at timestamp(6) not null, modified_at timestamp(6) not null, duration_ms bigint not null, last_read_comment_id bigint, post_id bigint not null, user_id bigint not null, primary key (view_history_id), constraint uk_view_histories_user_post unique (user_id, post_id));

create index idx_ad_click_logs_ad on ad_click_logs (ad_id, clicked_at);

create index idx_ad_click_logs_user on ad_click_logs (user_id);

create index idx_ads_active on ads (is_active, placement, start_date, end_date);

create index idx_agent_logs_agent_created on agent_activity_logs (agent_id, created_at);

create index idx_agent_logs_action_created on agent_activity_logs (action_type, created_at);

create index idx_agent_daily_quotas_lookup on agent_daily_quotas (agent_id, quota_date, action_type);

create index idx_agents_user_status on agents (user_id, status);

create index idx_agents_status_deleted on agents (status, is_deleted);

create index idx_board_categories_board on board_categories (board_id, is_active, sort_order);

create index idx_boards_active on boards (is_active, is_public, sort_order);

create index idx_boards_creator on boards (creator_id);

create index idx_comments_post on comments (post_id, is_deleted, created_at);

create index idx_comments_user on comments (user_id, is_deleted);

create index idx_comments_agent on comments (agent_id, is_deleted, created_at);

create index idx_comments_parent on comments (parent_id);

create index idx_common_code_details_type on common_code_details (type_code, is_active, sort_order);

create index idx_display_name_histories_user on display_name_histories (user_id, changed_at);

create index idx_display_name_histories_name on display_name_histories (previous_name);

create index idx_draft_posts_user on draft_posts (user_id, modified_at);

create index idx_emoticon_images_master on emoticon_images (emoticon_id, sort_order);

create index idx_emoticon_masters_active on emoticon_masters (is_active, created_at);

create index idx_emoticon_masters_creator on emoticon_masters (creator_id);

create index idx_emoticon_purchases_user on emoticon_purchases (user_id, created_at desc);

create index idx_emoticon_purchases_emoticon on emoticon_purchases (emoticon_id);

create index idx_error_logs_created on error_logs (created_at);

create index idx_error_logs_resolved on error_logs (is_resolved, created_at);

create index idx_error_logs_type on error_logs (error_type, created_at);

create index idx_error_logs_code on error_logs (error_code, created_at);

create index idx_error_logs_status on error_logs (http_status, created_at);

create index idx_files_uploader on files (uploader_id);

create index idx_files_related on files (related_type, related_id);

create index idx_login_histories_user on login_histories (user_id, created_at);

create index idx_login_histories_ip on login_histories (ip_address, created_at);

create index idx_login_histories_login_id on login_histories (login_id, created_at);

create index idx_logs_user on logs (user_id, created_at);

create index idx_logs_action on logs (action_type, created_at);

create index idx_message_queue_status on message_queue (status, requested_at);

create index idx_message_queue_processing_started on message_queue (status, processing_started_at);

create index idx_message_queue_user on message_queue (target_user_id);

create index idx_messages_receiver on messages (receiver_id, is_deleted_by_receiver, is_read, created_at desc);

create index idx_messages_sender on messages (sender_id, is_deleted_by_sender, created_at desc);

create index idx_notifications_user on notifications (user_id, is_read, created_at desc);

create index idx_password_histories_user on password_histories (user_id, created_at);

create index idx_point_histories_user on point_histories (user_id, created_at desc);

create index idx_popular_posts_type on popular_posts (ranking_type, rank);

create index idx_popular_posts_post on popular_posts (post_id);

create index idx_post_versions_post on post_versions (post_id, created_at);

create index idx_posts_board_created on posts (board_id, is_deleted, is_secret, created_at);

create index idx_posts_board_notice on posts (board_id, is_notice, is_secret, created_at);

create index idx_posts_user on posts (user_id, is_deleted, created_at);

create index idx_posts_agent on posts (agent_id, is_deleted, created_at);

create index idx_posts_category on posts (category_id);

create index idx_posts_popular on posts (board_id, is_deleted, is_secret, like_count, created_at);

create index idx_purchase_history_user on purchase_history (user_id, created_at desc);

create index idx_refresh_tokens_user on refresh_tokens (user_id, is_revoked);

create index idx_refresh_tokens_hash on refresh_tokens (token_hash);

create index idx_refresh_tokens_expires on refresh_tokens (expires_at);

create index idx_reports_status on reports (status, created_at desc);

create index idx_reports_reporter on reports (reporter_id);

create index idx_reports_target on reports (target_type, target_id);

create index idx_sanctions_user on sanctions (target_user_id, end_date);

create index idx_sanctions_admin on sanctions (admin_id);

create index idx_search_personalization_user on search_personalization (user_id, searched_at desc);

create index idx_search_statistics_date on search_statistics (search_date, search_count desc);

create index idx_search_statistics_keyword on search_statistics (keyword, search_date desc);

create index idx_shop_items_active on shop_items (is_active, item_type);

create index idx_tags_count on tags (post_count);

create index idx_user_blocks_target on user_blocks (target_id);

create index idx_user_feeds_user on user_feeds (target_user_id, is_read, created_at desc);

create index idx_view_histories_user on view_histories (user_id, created_at desc);

create index idx_view_histories_user_modified on view_histories (user_id, modified_at desc);

create index idx_view_histories_post on view_histories (post_id);

alter table if exists ad_click_logs add constraint FKr4ep53k5wh793h1kaqwbtgm70 foreign key (ad_id) references ads;

alter table if exists ad_click_logs add constraint FKma11sl0uxmxyj67alkxp6thli foreign key (user_id) references users;

alter table if exists admins add constraint FKfta8hcof8p861k7tx767it77u foreign key (board_id) references boards;

alter table if exists admins add constraint FKgc8dtql9mkq268detxiox7fpm foreign key (user_id) references users;

alter table if exists agent_activity_logs add constraint FK4hds6sstjsjhh1w7gbpmk0wra foreign key (agent_id) references agents;

alter table if exists agent_activity_logs add constraint FKbrgx0tkoixwrn2321slvvah5a foreign key (user_id) references users;

alter table if exists agent_daily_quotas add constraint FKih2xu0j0sl4oii838q598h8rs foreign key (agent_id) references agents;

alter table if exists agents add constraint FK2vh8rg4inh3scgcguimya35my foreign key (user_id) references users;

alter table if exists board_ai_info add constraint FKfkxiukvk0t3boa0lsgrsigqop foreign key (board_id) references boards;

alter table if exists board_categories add constraint FKnckgrc1tex85xdljrc6f6cuv foreign key (board_id) references boards;

alter table if exists board_subscriptions add constraint FKremft805u32orrbcj5atw92k foreign key (board_id) references boards;

alter table if exists board_subscriptions add constraint FKkip2j63144xdp43hkw0tnhhlf foreign key (user_id) references users;

alter table if exists boards add constraint FKtrkvr1mntwmts126iw6kltbgk foreign key (creator_id) references users;

alter table if exists comment_closures add constraint FK2q6ms4cu7ofhcaer8nhiwms5r foreign key (ancestor_id) references comments;

alter table if exists comment_closures add constraint FK6rh406l9x6dmyn2al5yephtsw foreign key (descendant_id) references comments;

alter table if exists comment_likes add constraint FK3wa5u7bs1p1o9hmavtgdgk1go foreign key (comment_id) references comments;

alter table if exists comment_likes add constraint FK6h3lbneryl5pyb9ykaju7werx foreign key (user_id) references users;

alter table if exists comment_versions add constraint FK8gkkmkg5c8hbigvej0u19t18 foreign key (comment_id) references comments;

alter table if exists comment_versions add constraint FKe05w093xg72as30e0om5nm9tp foreign key (modifier_id) references users;

alter table if exists comments add constraint FK5u0ui39kawiko0naw5dpoifi foreign key (agent_id) references agents;

alter table if exists comments add constraint FKlri30okf66phtcgbe5pok7cc0 foreign key (parent_id) references comments;

alter table if exists comments add constraint FKh4c7lvsc298whoyd4w9ta25cr foreign key (post_id) references posts;

alter table if exists comments add constraint FK8omq0tc18jd43bu5tjh6jvraq foreign key (user_id) references users;

alter table if exists common_code_details add constraint FKgx8jk9eqftfvmn2j1jvqn6ous foreign key (type_code) references common_codes;

alter table if exists display_name_histories add constraint FK7t4ieg0kf2akyt974vaeq35r4 foreign key (user_id) references users;

alter table if exists draft_posts add constraint FKg7m3xx1yepu37um12fbcq4100 foreign key (board_id) references boards;

alter table if exists draft_posts add constraint FKcamf2kablhwib4g1bnsvk3gna foreign key (category_id) references board_categories;

alter table if exists draft_posts add constraint FK8qylnq0uefkruld80jh0wfxox foreign key (original_post_id) references posts;

alter table if exists draft_posts add constraint FKgqoej2lhbrntcet0jligqs0q8 foreign key (user_id) references users;

alter table if exists emoticon_images add constraint FKqm37xku346o8v05em5h5pkxmk foreign key (emoticon_id) references emoticon_masters;

alter table if exists emoticon_masters add constraint FK474vb0wx1c5m50xn44g6fl5on foreign key (creator_id) references users;

alter table if exists emoticon_purchases add constraint FK9nosxpn4xy3tkrf4fgcma5gcs foreign key (emoticon_id) references emoticon_masters;

alter table if exists emoticon_purchases add constraint FKieqi5idgfyvgrljjivp26g9pe foreign key (user_id) references users;

alter table if exists files add constraint FKhaj8rngy0ky91ndcqv2isi9cr foreign key (uploader_id) references users;

alter table if exists ip_blocks add constraint FKqhduvgk8wecoabgc141i8847w foreign key (admin_id) references admins;

alter table if exists login_histories add constraint FKo6o8fq7e5r8aq31dydpe05828 foreign key (user_id) references users;

alter table if exists message_queue add constraint FKi4gslghub6l2theweneqq9ocj foreign key (target_user_id) references users;

alter table if exists messages add constraint FKt05r0b6n0iis8u7dfna4xdh73 foreign key (receiver_id) references users;

alter table if exists messages add constraint FK4ui4nnwntodh6wjvck53dbk9m foreign key (sender_id) references users;

alter table if exists notifications add constraint FK4sd9fik0uthbk6d9rsxco4uja foreign key (actor_id) references users;

alter table if exists notifications add constraint FKiac5nf1b9qkf5nedpkxl5gfd3 foreign key (actor_agent_id) references agents;

alter table if exists notifications add constraint FK9y21adhxn0ayjhfocscqox7bh foreign key (user_id) references users;

alter table if exists password_histories add constraint FKgmv6bm0fbiiufyxgx80c9dfn6 foreign key (user_id) references users;

alter table if exists password_reset_tokens add constraint FKk3ndxg5xp6v7wd4gjyusp15gq foreign key (user_id) references users;

alter table if exists point_histories add constraint FKp1n0qput9f88pa5lwy2nsr19f foreign key (user_id) references users;

alter table if exists popular_posts add constraint FK1ai70alvj1bvaaeceogk8qd38 foreign key (post_id) references posts;

alter table if exists post_likes add constraint FKa5wxsgl4doibhbed9gm7ikie2 foreign key (post_id) references posts;

alter table if exists post_likes add constraint FKkgau5n0nlewg6o9lr4yibqgxj foreign key (user_id) references users;

alter table if exists post_tags add constraint FKkifam22p4s1nm3bkmp1igcn5w foreign key (post_id) references posts;

alter table if exists post_tags add constraint FKm6cfovkyqvu5rlm6ahdx3eavj foreign key (tag_id) references tags;

alter table if exists post_versions add constraint FKbpnj9gtspr5yegaclih2nuon foreign key (modifier_id) references users;

alter table if exists post_versions add constraint FK6886p1jjrs7n4cohh91ba2qsm foreign key (post_id) references posts;

alter table if exists posts add constraint FK6eixtubav8l7qmcp364b2h9w0 foreign key (agent_id) references agents;

alter table if exists posts add constraint FK78qo1gxd85rcxqojt2cpcmuj6 foreign key (board_id) references boards;

alter table if exists posts add constraint FKrer9p6rs4648a42y8qwaj2r1f foreign key (category_id) references board_categories;

alter table if exists posts add constraint FK5lidm6cqbc7u4xhqpxm898qme foreign key (user_id) references users;

alter table if exists purchase_history add constraint FKs12kpxkex20fn75qlcc35vgoo foreign key (item_id) references shop_items;

alter table if exists purchase_history add constraint FKjli24jp4h6ny76h90kbp65cal foreign key (user_id) references users;

alter table if exists refresh_tokens add constraint FK1lih5y2npsf8u5o3vhdb9y0os foreign key (user_id) references users;

alter table if exists reports add constraint FKgf2j1bmsrm2r54u0bvmt98uof foreign key (admin_id) references admins;

alter table if exists reports add constraint FKd3qiw2om5d2oh5xb7fbdcq225 foreign key (reporter_id) references users;

alter table if exists sanctions add constraint FKeom516mv9qh60iv7di9deqygi foreign key (admin_id) references admins;

alter table if exists sanctions add constraint FK380w5ealmji8s7ipik18xwi2j foreign key (target_user_id) references users;

alter table if exists scraps add constraint FKfhp2rbuhodh4lisy2n7oh22va foreign key (post_id) references posts;

alter table if exists scraps add constraint FKqd3nh3tj8ru0ubnk54qckuh42 foreign key (user_id) references users;

alter table if exists search_personalization add constraint FKmljxlax8w5bilay1gqaxbsvib foreign key (user_id) references users;

alter table if exists social_accounts add constraint FK6rmxxiton5yuvu7ph2hcq2xn7 foreign key (user_id) references users;

alter table if exists user_blocks add constraint FKtrradpkxabn0u5922khoxc0k0 foreign key (target_id) references users;

alter table if exists user_blocks add constraint FKqjk3v8efx104494evnp1yxaxj foreign key (user_id) references users;

alter table if exists user_feeds add constraint FKfsh2b3l97bps8egmrcfar4h27 foreign key (target_user_id) references users;

alter table if exists user_notification_settings add constraint FKs9tjvxu8ko31ivjlq9l9duh9y foreign key (user_id) references users;

alter table if exists user_points add constraint FKs9hv38cn8bnkxfop9ohaofwo1 foreign key (user_id) references users;

alter table if exists user_settings add constraint FK8v82nj88rmai0nyck19f873dw foreign key (user_id) references users;

alter table if exists view_histories add constraint FKo3g07auw4u9f2q2pd6ig80u7x foreign key (last_read_comment_id) references comments;

alter table if exists view_histories add constraint FKk9sv0r6xopkkq32esysuv96wv foreign key (post_id) references posts;

alter table if exists view_histories add constraint FKjcxu9qyprbfx1lljwucpq840d foreign key (user_id) references users;

