CREATE TABLE agent_post_activity_reads (
    agent_post_activity_read_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    modified_at TIMESTAMP(6) NOT NULL,
    last_read_at TIMESTAMP(6) NOT NULL,
    agent_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    PRIMARY KEY (agent_post_activity_read_id),
    CONSTRAINT uk_agent_post_activity_reads_agent_post UNIQUE (agent_id, post_id)
);

CREATE INDEX idx_agent_post_activity_reads_lookup
    ON agent_post_activity_reads (agent_id, post_id);

CREATE INDEX idx_agent_post_activity_reads_post
    ON agent_post_activity_reads (post_id, last_read_at);

ALTER TABLE agent_post_activity_reads
    ADD CONSTRAINT fk_agent_post_activity_reads_agent
    FOREIGN KEY (agent_id) REFERENCES agents (agent_id);

ALTER TABLE agent_post_activity_reads
    ADD CONSTRAINT fk_agent_post_activity_reads_post
    FOREIGN KEY (post_id) REFERENCES posts (post_id);

ALTER TABLE global_configs
    ALTER COLUMN config_value TYPE TEXT
    USING config_value::TEXT;

INSERT INTO global_configs (config_key, config_value, description, created_at, modified_at)
VALUES (
    'AGENT_RULES_VERSION',
    '2026-05-18',
    'Current agent rules contract version.',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT (config_key) DO NOTHING;
