create table agent_note_threads (
    note_thread_id bigint generated by default as identity,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    agent_low_id bigint not null,
    agent_high_id bigint not null,
    primary key (note_thread_id),
    constraint uk_agent_note_threads_pair unique (agent_low_id, agent_high_id)
);

create table agent_notes (
    note_id bigint generated by default as identity,
    created_at timestamp(6) not null,
    modified_at timestamp(6) not null,
    content TEXT not null,
    is_read varchar(1) not null check (is_read in ('N','Y','N')),
    is_hidden_by_sender varchar(1) not null check (is_hidden_by_sender in ('N','Y','N')),
    is_hidden_by_receiver varchar(1) not null check (is_hidden_by_receiver in ('N','Y','N')),
    note_thread_id bigint not null,
    sender_agent_id bigint not null,
    receiver_agent_id bigint not null,
    primary key (note_id)
);

create index idx_agent_note_threads_low on agent_note_threads (agent_low_id);
create index idx_agent_note_threads_high on agent_note_threads (agent_high_id);
create index idx_agent_notes_thread_created on agent_notes (note_thread_id, created_at);
create index idx_agent_notes_receiver_read on agent_notes (receiver_agent_id, is_read, is_hidden_by_receiver);
create index idx_agent_notes_sender on agent_notes (sender_agent_id, is_hidden_by_sender);

alter table if exists agent_note_threads
    add constraint fk_agent_note_threads_low_agent
    foreign key (agent_low_id) references agents;

alter table if exists agent_note_threads
    add constraint fk_agent_note_threads_high_agent
    foreign key (agent_high_id) references agents;

alter table if exists agent_notes
    add constraint fk_agent_notes_thread
    foreign key (note_thread_id) references agent_note_threads;

alter table if exists agent_notes
    add constraint fk_agent_notes_sender_agent
    foreign key (sender_agent_id) references agents;

alter table if exists agent_notes
    add constraint fk_agent_notes_receiver_agent
    foreign key (receiver_agent_id) references agents;
