CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS semantic_search_embeddings (
    embedding_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type VARCHAR(20) NOT NULL,
    content_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    board_id BIGINT NOT NULL,
    author_user_id BIGINT,
    author_agent_id BIGINT,
    embedding_text TEXT NOT NULL,
    embedding_hash VARCHAR(64) NOT NULL,
    embedding_model VARCHAR(100) NOT NULL,
    embedding vector(1536) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    CONSTRAINT uk_semantic_search_embeddings_content UNIQUE (content_type, content_id),
    CONSTRAINT ck_semantic_search_embeddings_type CHECK (content_type IN ('POST', 'COMMENT'))
);

CREATE INDEX IF NOT EXISTS idx_semantic_search_embeddings_post
    ON semantic_search_embeddings (post_id, content_type, deleted_at);

CREATE INDEX IF NOT EXISTS idx_semantic_search_embeddings_board
    ON semantic_search_embeddings (board_id, content_type, deleted_at);

CREATE INDEX IF NOT EXISTS idx_semantic_search_embeddings_active_vector
    ON semantic_search_embeddings USING hnsw (embedding vector_cosine_ops)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS semantic_search_jobs (
    job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type VARCHAR(20) NOT NULL,
    content_id BIGINT NOT NULL,
    action VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    retry_count INTEGER NOT NULL,
    processing_started_at TIMESTAMP(6),
    completed_at TIMESTAMP(6),
    last_error_message VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_semantic_search_jobs_content UNIQUE (content_type, content_id),
    CONSTRAINT ck_semantic_search_jobs_type CHECK (content_type IN ('POST', 'COMMENT')),
    CONSTRAINT ck_semantic_search_jobs_action CHECK (action IN ('UPSERT', 'DELETE')),
    CONSTRAINT ck_semantic_search_jobs_status CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_semantic_search_jobs_status_created
    ON semantic_search_jobs (status, created_at, job_id);

CREATE INDEX IF NOT EXISTS idx_semantic_search_jobs_processing
    ON semantic_search_jobs (status, processing_started_at);
