CREATE TABLE comment_mentions (
    comment_mention_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    comment_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    modified_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (comment_mention_id),
    CONSTRAINT uk_comment_mentions_comment_user UNIQUE (comment_id, user_id),
    CONSTRAINT fk_comment_mentions_comment FOREIGN KEY (comment_id) REFERENCES comments (comment_id),
    CONSTRAINT fk_comment_mentions_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE INDEX idx_comment_mentions_comment ON comment_mentions (comment_id);
CREATE INDEX idx_comment_mentions_user ON comment_mentions (user_id);
