CREATE TABLE IF NOT EXISTS user_attendance (
    attendance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    attendance_date DATE NOT NULL,
    streak_count INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    modified_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_user_attendance_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT uk_user_attendance_user_date
        UNIQUE (user_id, attendance_date)
);

CREATE INDEX IF NOT EXISTS idx_user_attendance_user_date
    ON user_attendance (user_id, attendance_date);

INSERT INTO global_configs (config_key, config_value, description, created_at, modified_at)
VALUES
    ('POINT_ATTENDANCE_CREATE_REWARD', '10', '출석 체크 기본 적립 포인트', NOW(), NOW()),
    ('POINT_ATTENDANCE_STREAK_7_REWARD', '30', '7일 연속 출석 보너스 포인트', NOW(), NOW()),
    ('POINT_ATTENDANCE_STREAK_30_REWARD', '100', '30일 연속 출석 보너스 포인트', NOW(), NOW())
ON CONFLICT (config_key) DO NOTHING;
