CREATE TABLE IF NOT EXISTS badges (
    badge_code VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL,
    icon VARCHAR(80) NOT NULL,
    tier VARCHAR(20) NOT NULL,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    modified_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_badges_tier CHECK (tier IN ('BRONZE', 'SILVER', 'GOLD'))
);

CREATE TABLE IF NOT EXISTS user_badges (
    user_badge_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    badge_code VARCHAR(50) NOT NULL,
    acquired_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    modified_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_user_badges_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_user_badges_badge
        FOREIGN KEY (badge_code) REFERENCES badges(badge_code),
    CONSTRAINT uk_user_badges_user_badge
        UNIQUE (user_id, badge_code)
);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS representative_badge_code VARCHAR(50);

CREATE INDEX IF NOT EXISTS idx_user_badges_user_acquired
    ON user_badges (user_id, acquired_at DESC, user_badge_id DESC);

INSERT INTO badges (badge_code, name, description, icon, tier, sort_order, created_at, modified_at)
VALUES
    ('FIRST_POST', 'First Post', 'Awarded after writing the first post.', 'edit-3', 'BRONZE', 10, NOW(), NOW()),
    ('POSTS_10', '10 Posts', 'Awarded after writing 10 posts.', 'files', 'SILVER', 20, NOW(), NOW()),
    ('POSTS_100', '100 Posts', 'Awarded after writing 100 posts.', 'library', 'GOLD', 30, NOW(), NOW()),
    ('FIRST_COMMENT', 'First Comment', 'Awarded after writing the first comment.', 'message-circle', 'BRONZE', 40, NOW(), NOW()),
    ('COMMENTS_10', '10 Comments', 'Awarded after writing 10 comments.', 'messages-square', 'SILVER', 50, NOW(), NOW()),
    ('COMMENTS_100', '100 Comments', 'Awarded after writing 100 comments.', 'message-square-text', 'GOLD', 60, NOW(), NOW()),
    ('ATTENDANCE_7', '7 Day Streak', 'Awarded after 7 consecutive attendance check-ins.', 'calendar-check', 'SILVER', 70, NOW(), NOW()),
    ('ATTENDANCE_30', '30 Day Streak', 'Awarded after 30 consecutive attendance check-ins.', 'calendar-days', 'GOLD', 80, NOW(), NOW()),
    ('POPULAR_POST_10', 'Popular Post 10', 'Awarded when one of your posts reaches 10 likes.', 'heart', 'SILVER', 90, NOW(), NOW()),
    ('POPULAR_POST_50', 'Popular Post 50', 'Awarded when one of your posts reaches 50 likes.', 'flame', 'GOLD', 100, NOW(), NOW())
ON CONFLICT (badge_code) DO NOTHING;

DO $$
BEGIN
    ALTER TABLE user_notification_settings
        DROP CONSTRAINT IF EXISTS user_notification_settings_notification_type_check;
    ALTER TABLE user_notification_settings
        DROP CONSTRAINT IF EXISTS ck_user_notification_settings_type;
    ALTER TABLE user_notification_settings
        ADD CONSTRAINT user_notification_settings_notification_type_check
            CHECK (notification_type IN ('LIKE', 'COMMENT', 'REPLY', 'MENTION', 'MESSAGE', 'SYSTEM', 'SANCTION', 'KEYWORD', 'BADGE'));
END $$;

INSERT INTO common_code_details (type_code, code_value, code_name, sort_order, is_active, created_at, modified_at)
SELECT 'NOTIFICATION_TYPE',
       'BADGE',
       'Badge notification',
       90,
       'Y',
       NOW(),
       NOW()
WHERE NOT EXISTS (
    SELECT 1
    FROM common_code_details
    WHERE type_code = 'NOTIFICATION_TYPE'
      AND code_value = 'BADGE'
);
