CREATE TABLE IF NOT EXISTS scheduled_posts (
    scheduled_post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    board_id BIGINT NOT NULL,
    category_id BIGINT,
    title VARCHAR(200) NOT NULL,
    contents TEXT NOT NULL,
    is_notice VARCHAR(1) NOT NULL DEFAULT 'N',
    is_nsfw VARCHAR(1) NOT NULL DEFAULT 'N',
    is_spoiler VARCHAR(1) NOT NULL DEFAULT 'N',
    is_secret VARCHAR(1) NOT NULL DEFAULT 'N',
    tags_json TEXT,
    file_ids_json TEXT,
    poll_json TEXT,
    series_id BIGINT,
    scheduled_at TIMESTAMP(6) NOT NULL,
    status VARCHAR(20) NOT NULL,
    published_post_id BIGINT,
    failure_reason VARCHAR(255),
    processing_started_at TIMESTAMP(6),
    published_at TIMESTAMP(6),
    canceled_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    modified_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_scheduled_posts_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_scheduled_posts_board
        FOREIGN KEY (board_id) REFERENCES boards(board_id),
    CONSTRAINT fk_scheduled_posts_category
        FOREIGN KEY (category_id) REFERENCES board_categories(category_id),
    CONSTRAINT fk_scheduled_posts_published_post
        FOREIGN KEY (published_post_id) REFERENCES posts(post_id),
    CONSTRAINT ck_scheduled_posts_status
        CHECK (status IN ('SCHEDULED', 'PUBLISHING', 'PUBLISHED', 'CANCELED', 'FAILED')),
    CONSTRAINT ck_scheduled_posts_bool_notice CHECK (is_notice IN ('Y', 'N')),
    CONSTRAINT ck_scheduled_posts_bool_nsfw CHECK (is_nsfw IN ('Y', 'N')),
    CONSTRAINT ck_scheduled_posts_bool_spoiler CHECK (is_spoiler IN ('Y', 'N')),
    CONSTRAINT ck_scheduled_posts_bool_secret CHECK (is_secret IN ('Y', 'N'))
);

CREATE INDEX IF NOT EXISTS idx_scheduled_posts_due
    ON scheduled_posts (status, scheduled_at, scheduled_post_id);

CREATE INDEX IF NOT EXISTS idx_scheduled_posts_user_status
    ON scheduled_posts (user_id, status, scheduled_at DESC, scheduled_post_id DESC);
