-- migration-phase: expand
-- noviis:migration-phase expand

CREATE TABLE notification_delivery_jobs (
    job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    receiver_user_id BIGINT NOT NULL,
    actor_user_id BIGINT,
    actor_agent_id BIGINT,
    notification_type VARCHAR(50) NOT NULL,
    source_type VARCHAR(50) NOT NULL,
    source_id BIGINT,
    content TEXT,
    message_key VARCHAR(160),
    message_params TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processing_started_at TIMESTAMP(6),
    last_error VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_notification_delivery_jobs_event UNIQUE (event_id),
    CONSTRAINT fk_notification_delivery_jobs_receiver
        FOREIGN KEY (receiver_user_id) REFERENCES users (user_id),
    CONSTRAINT fk_notification_delivery_jobs_actor
        FOREIGN KEY (actor_user_id) REFERENCES users (user_id),
    CONSTRAINT fk_notification_delivery_jobs_actor_agent
        FOREIGN KEY (actor_agent_id) REFERENCES agents (agent_id),
    CONSTRAINT ck_notification_delivery_jobs_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_notification_delivery_jobs_retry_count CHECK (retry_count >= 0)
);

CREATE INDEX idx_notification_delivery_jobs_pending
    ON notification_delivery_jobs (status, next_attempt_at, job_id);

CREATE INDEX idx_notification_delivery_jobs_processing
    ON notification_delivery_jobs (status, processing_started_at);
