-- migration-phase: expand
-- noviis:migration-phase expand

ALTER TABLE notification_delivery_jobs
    ADD COLUMN failure_code VARCHAR(50),
    ADD COLUMN first_failed_at TIMESTAMP(6),
    ADD COLUMN last_failed_at TIMESTAMP(6),
    ADD COLUMN redrive_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE notification_delivery_jobs
    ADD CONSTRAINT ck_notification_delivery_jobs_redrive_count CHECK (redrive_count >= 0);

CREATE TABLE keyword_notification_fanout_jobs (
    fanout_job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    last_subscription_id BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processing_started_at TIMESTAMP(6),
    last_error VARCHAR(160),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_keyword_notification_fanout_post UNIQUE (post_id),
    CONSTRAINT fk_keyword_notification_fanout_post FOREIGN KEY (post_id) REFERENCES posts (post_id),
    CONSTRAINT ck_keyword_notification_fanout_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_keyword_notification_fanout_retry_count CHECK (retry_count >= 0)
);

CREATE INDEX idx_keyword_notification_fanout_due
    ON keyword_notification_fanout_jobs (status, next_attempt_at, fanout_job_id);
