-- migration-phase: expand
-- noviis:migration-phase expand

CREATE TABLE semantic_search_reindex_jobs (
    reindex_job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type VARCHAR(30) NOT NULL,
    scope_id BIGINT NOT NULL,
    content_phase VARCHAR(20) NOT NULL,
    last_content_id BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    processing_started_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_semantic_search_reindex_scope UNIQUE (scope_type, scope_id),
    CONSTRAINT ck_semantic_search_reindex_scope CHECK (scope_type IN ('POST_COMMENTS', 'BOARD')),
    CONSTRAINT ck_semantic_search_reindex_phase CHECK (content_phase IN ('POST', 'COMMENT')),
    CONSTRAINT ck_semantic_search_reindex_status CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED'))
);

CREATE INDEX idx_semantic_search_reindex_pending
    ON semantic_search_reindex_jobs (status, updated_at, reindex_job_id);
