-- noviis:migration-phase expand

CREATE TABLE push_delivery_jobs (
    job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    subscription_id BIGINT NOT NULL,
    receiver_user_id BIGINT NOT NULL,
    endpoint VARCHAR(500) NOT NULL,
    p256dh VARCHAR(255) NOT NULL,
    auth VARCHAR(255) NOT NULL,
    subscription_modified_at TIMESTAMP(6) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processing_started_at TIMESTAMP(6),
    last_error VARCHAR(500),
    first_failed_at TIMESTAMP(6),
    last_failed_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_push_delivery_jobs_event_subscription UNIQUE (event_id, subscription_id),
    CONSTRAINT ck_push_delivery_jobs_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'EXPIRED', 'FAILED')),
    CONSTRAINT ck_push_delivery_jobs_retry_count CHECK (retry_count >= 0)
);

CREATE INDEX idx_push_delivery_jobs_due
    ON push_delivery_jobs (status, next_attempt_at, job_id);

CREATE INDEX idx_push_delivery_jobs_processing
    ON push_delivery_jobs (status, processing_started_at);
