package com.weedrice.whiteboard.domain.emoticon.service;

import com.weedrice.whiteboard.domain.board.service.BoardAccessPolicy;
import com.weedrice.whiteboard.domain.emoticon.dto.EmoticonUpdateRequest;
import com.weedrice.whiteboard.domain.emoticon.entity.EmoticonImage;
import com.weedrice.whiteboard.domain.emoticon.entity.EmoticonMaster;
import com.weedrice.whiteboard.domain.emoticon.entity.EmoticonPurchase;
import com.weedrice.whiteboard.domain.emoticon.repository.EmoticonImageRepository;
import com.weedrice.whiteboard.domain.emoticon.repository.EmoticonMasterRepository;
import com.weedrice.whiteboard.domain.emoticon.repository.EmoticonPurchaseRepository;
import com.weedrice.whiteboard.domain.file.entity.File;
import com.weedrice.whiteboard.domain.file.entity.FileStorageStatus;
import com.weedrice.whiteboard.domain.file.repository.FileRepository;
import com.weedrice.whiteboard.domain.file.service.FileDownloadService;
import com.weedrice.whiteboard.domain.file.service.FileService;
import com.weedrice.whiteboard.domain.file.support.FileUrlResolver;
import com.weedrice.whiteboard.domain.inquiry.service.InquiryReadService;
import com.weedrice.whiteboard.domain.post.service.PostAccessPolicy;
import com.weedrice.whiteboard.domain.shop.entity.ShopItem;
import com.weedrice.whiteboard.domain.user.entity.User;
import com.weedrice.whiteboard.domain.user.repository.UserRepository;
import com.weedrice.whiteboard.domain.user.service.UserBlockService;
import com.weedrice.whiteboard.domain.user.service.UserWritableResolver;
import com.weedrice.whiteboard.global.common.util.FileStorageService;
import com.weedrice.whiteboard.global.config.QuerydslConfig;
import com.weedrice.whiteboard.global.exception.BusinessException;
import com.weedrice.whiteboard.global.exception.ErrorCode;
import jakarta.persistence.EntityManager;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.FilterType;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.jdbc.Sql;

import java.io.ByteArrayInputStream;
import java.time.Clock;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

@DataJpaTest
@Import({QuerydslConfig.class, FileDownloadService.class, EmoticonImageRetentionTest.TestConfig.class})
@Sql(statements = """
        CREATE TABLE IF NOT EXISTS emoticon_masters (
            is_active VARCHAR(1) NOT NULL,
            purchase_count INTEGER NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            creator_id BIGINT,
            emoticon_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            modified_at TIMESTAMP(6) NOT NULL,
            name VARCHAR(100) NOT NULL,
            thumbnail_url VARCHAR(500),
            tags VARCHAR ARRAY
        );
        """)
class EmoticonImageRetentionTest {

    @Autowired private EmoticonService emoticonService;
    @Autowired private FileDownloadService fileDownloadService;
    @Autowired private FileRepository fileRepository;
    @Autowired private EmoticonMasterRepository emoticonMasterRepository;
    @Autowired private EmoticonImageRepository emoticonImageRepository;
    @Autowired private EmoticonPurchaseRepository purchaseRepository;
    @Autowired private UserRepository userRepository;
    @Autowired private UserWritableResolver userWritableResolver;
    @Autowired private FileStorageService storage;
    @Autowired private EntityManager entityManager;

    private User owner;
    private EmoticonMaster master;
    private File removedFile;
    private File currentFile;
    private Long removedImageId;

    @BeforeEach
    void seed() {
        owner = createUser("owner");
        when(userWritableResolver.resolveForUpdate(owner.getUserId())).thenReturn(owner);
        master = emoticonMasterRepository.save(EmoticonMaster.builder()
                .name("Image retention").creator(owner).tags(List.of()).build());
        removedFile = createFile("removed.png");
        currentFile = createFile("current.png");
        EmoticonImage removedImage = EmoticonImage.builder()
                .imageUrl(FileUrlResolver.resolve(removedFile.getFileId())).sortOrder(0).build();
        master.addImage(removedImage);
        master.addImage(EmoticonImage.builder()
                .imageUrl(FileUrlResolver.resolve(currentFile.getFileId())).sortOrder(1).build());
        entityManager.flush();
        removedImageId = removedImage.getImageId();
    }

    @Test
    void removedImageLeavesPickerButItsExistingUrlRemainsDownloadable() throws Exception {
        removeImage();
        assertThat(emoticonImageRepository.findById(removedImageId)).isEmpty();
        assertThat(emoticonService.getEmoticonDetail(master.getEmoticonId(), null).getImages())
                .extracting("imageUrl").containsExactly(FileUrlResolver.resolve(currentFile.getFileId()));
        File retained = fileRepository.findById(removedFile.getFileId()).orElseThrow();
        assertThat(retained.getStorageStatus()).isEqualTo(FileStorageStatus.ACTIVE);
        assertThat(retained.getRelatedId()).isEqualTo(master.getEmoticonId());
        assertThat(retained.getRelatedType()).isEqualTo(FileService.RELATED_TYPE_EMOTICON_IMAGE);
        when(storage.loadFile("retention/removed.png"))
                .thenReturn(new ByteArrayInputStream(new byte[] {1, 2, 3}));

        var download = fileDownloadService.downloadFile(removedFile.getFileId(), null);
        assertThat(download.freshnessCacheable()).isTrue();
        try (var input = download.inputStream()) {
            assertThat(input.readAllBytes()).containsExactly((byte) 1, (byte) 2, (byte) 3);
        }
    }

    @Test
    void removedImageKeepsHiddenPackOwnerAndBuyerAccessRules() {
        User buyer = createUser("buyer");
        User other = createUser("other");
        purchaseRepository.save(EmoticonPurchase.builder()
                .emoticon(master).user(buyer).purchasedPrice(100).build());
        master.deactivate();
        removeImage();

        assertThat(fileDownloadService.downloadFile(removedFile.getFileId(), owner.getUserId())
                .freshnessCacheable()).isFalse();
        assertThat(fileDownloadService.downloadFile(removedFile.getFileId(), buyer.getUserId())
                .freshnessCacheable()).isFalse();
        assertAccessRejected(removedFile.getFileId(), null, ErrorCode.FORBIDDEN);
        assertAccessRejected(removedFile.getFileId(), other.getUserId(), ErrorCode.FORBIDDEN);
    }

    @Test
    void deletingPackCleansUpCurrentAndPreviouslyRemovedImages() {
        removeImage();
        emoticonService.deleteEmoticon(owner.getUserId(), master.getEmoticonId());
        entityManager.flush();
        entityManager.clear();

        assertThat(emoticonMasterRepository.findById(master.getEmoticonId())).isEmpty();
        for (Long fileId : List.of(removedFile.getFileId(), currentFile.getFileId())) {
            assertThat(fileRepository.findById(fileId).orElseThrow().getStorageStatus())
                    .isEqualTo(FileStorageStatus.PENDING_DELETE);
            assertAccessRejected(fileId, owner.getUserId(), ErrorCode.NOT_FOUND);
        }
    }

    @Test
    void purchaseHistoryStillPreventsDeletingPackAndRetainedFiles() {
        User buyer = createUser("buyer");
        purchaseRepository.save(EmoticonPurchase.builder()
                .emoticon(master).user(buyer).purchasedPrice(100).build());
        removeImage();

        assertThatThrownBy(() -> emoticonService.deleteEmoticon(owner.getUserId(), master.getEmoticonId()))
                .isInstanceOf(BusinessException.class)
                .hasFieldOrPropertyWithValue("errorCode", ErrorCode.VALIDATION_ERROR);
        assertThat(fileRepository.findById(removedFile.getFileId()).orElseThrow().getStorageStatus())
                .isEqualTo(FileStorageStatus.ACTIVE);
        assertThat(emoticonMasterRepository.findById(master.getEmoticonId())).isPresent();
    }

    private void removeImage() {
        emoticonService.updateEmoticon(owner.getUserId(), master.getEmoticonId(),
                EmoticonUpdateRequest.builder().deleteImageIds(List.of(removedImageId)).build());
        entityManager.flush();
        entityManager.clear();
    }

    private void assertAccessRejected(Long fileId, Long viewerId, ErrorCode code) {
        assertThatThrownBy(() -> fileDownloadService.downloadFile(fileId, viewerId))
                .isInstanceOf(BusinessException.class).hasFieldOrPropertyWithValue("errorCode", code);
    }

    private User createUser(String name) {
        return userRepository.save(User.builder().loginId("retention-" + name)
                .email("retention-" + name + "@example.com").password("password")
                .displayName(name).build());
    }

    private File createFile(String name) {
        return fileRepository.save(File.builder().filePath("retention/" + name).originalName(name)
                .mimeType("image/png").fileSize(3L).uploader(owner)
                .relatedId(master.getEmoticonId()).relatedType(FileService.RELATED_TYPE_EMOTICON_IMAGE).build());
    }

    @TestConfiguration
    @ComponentScan(basePackageClasses = FileDownloadService.class, useDefaultFilters = false,
            includeFilters = @ComponentScan.Filter(type = FilterType.REGEX,
                    pattern = "com\\.weedrice\\.whiteboard\\.domain\\.file\\.service\\.FileAccessService"))
    static class TestConfig {
        @Bean Clock clock() { return Clock.systemUTC(); }
        @Bean UserWritableResolver userWritableResolver() { return mock(UserWritableResolver.class); }
        @Bean FileStorageService storage() { return mock(FileStorageService.class); }
        @Bean BoardAccessPolicy boardAccessPolicy() { return mock(BoardAccessPolicy.class); }
        @Bean PostAccessPolicy postAccessPolicy() { return mock(PostAccessPolicy.class); }
        @Bean UserBlockService userBlockService() { return mock(UserBlockService.class); }
        @Bean InquiryReadService inquiryReadService() { return mock(InquiryReadService.class); }
        @Bean FileService fileService(FileRepository files, Clock clock) {
            return new FileService(null, null, files, null, clock);
        }
        @Bean EmoticonService emoticonService(EmoticonMasterRepository masters,
                EmoticonPurchaseRepository purchases, UserRepository users,
                UserWritableResolver writableUsers, FileService files, Clock clock) {
            EmoticonImageLimitPolicy limit = mock(EmoticonImageLimitPolicy.class);
            when(limit.getCurrentLimit()).thenReturn(20);
            EmoticonShopItemLifecycleService items = mock(EmoticonShopItemLifecycleService.class);
            when(items.lockForUpdate(anyLong())).thenReturn(ShopItem.builder()
                    .itemName("Retention test").price(100).itemType("EMOTICON").targetId(1L).build());
            return new EmoticonService(new EmoticonCatalogService(masters, users, clock),
                    new EmoticonCommandService(masters, writableUsers, new EmoticonAttachmentHelper(files),
                            new EmoticonDeletePolicy(purchases), limit, items,
                            FileService.RELATED_TYPE_EMOTICON_THUMBNAIL, FileService.RELATED_TYPE_EMOTICON_IMAGE),
                    null);
        }
    }
}
