package com.weedrice.whiteboard.domain.emoticon.service;

import com.weedrice.whiteboard.domain.emoticon.dto.EmoticonCreateRequest;
import com.weedrice.whiteboard.domain.emoticon.dto.EmoticonUpdateRequest;
import com.weedrice.whiteboard.domain.emoticon.entity.EmoticonImage;
import com.weedrice.whiteboard.domain.emoticon.entity.EmoticonMaster;
import com.weedrice.whiteboard.domain.emoticon.repository.EmoticonImageRepository;
import com.weedrice.whiteboard.domain.emoticon.repository.EmoticonMasterRepository;
import com.weedrice.whiteboard.domain.file.entity.File;
import com.weedrice.whiteboard.domain.file.entity.FileStorageStatus;
import com.weedrice.whiteboard.domain.file.repository.FileRepository;
import com.weedrice.whiteboard.domain.file.service.FileService;
import com.weedrice.whiteboard.domain.file.support.FileUrlResolver;
import com.weedrice.whiteboard.domain.shop.entity.ShopItem;
import com.weedrice.whiteboard.domain.user.entity.User;
import com.weedrice.whiteboard.domain.user.repository.UserRepository;
import com.weedrice.whiteboard.domain.user.service.UserWritableResolver;
import com.weedrice.whiteboard.global.config.QuerydslConfig;
import com.weedrice.whiteboard.global.exception.BusinessException;
import com.weedrice.whiteboard.global.exception.ErrorCode;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.ArgumentMatchers.anyList;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.reset;
import static org.mockito.Mockito.when;

@DataJpaTest
@Import({
        QuerydslConfig.class,
        EmoticonUpdateTransactionRollbackTest.TestConfig.class
})
@Sql(statements = """
        CREATE TABLE IF NOT EXISTS emoticon_masters (
            is_active VARCHAR(1) NOT NULL,
            purchase_count INTEGER NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            creator_id BIGINT,
            emoticon_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            modified_at TIMESTAMP(6) NOT NULL,
            name VARCHAR(100) NOT NULL,
            thumbnail_url VARCHAR(500),
            tags VARCHAR ARRAY
        );
        """)
@Transactional(propagation = Propagation.NOT_SUPPORTED)
class EmoticonUpdateTransactionRollbackTest {

    private static final String EMOTICON_IMAGE_TYPE = "EMOTICON_IMAGE";

    @Autowired
    private TransactionalEmoticonUpdater updater;
    @Autowired
    private TestDataService testDataService;
    @Autowired
    private EmoticonMasterRepository emoticonMasterRepository;
    @Autowired
    private EmoticonImageRepository emoticonImageRepository;
    @Autowired
    private FileRepository fileRepository;
    @Autowired
    private FileService fileService;
    @Autowired
    private UserWritableResolver userWritableResolver;
    @Autowired
    private EmoticonImageLimitPolicy imageLimitPolicy;
    @Autowired
    private EmoticonShopItemLifecycleService shopItemLifecycleService;
    @Autowired
    private UserRepository userRepository;

    @BeforeEach
    void setUpFileStateChanges() {
        reset(shopItemLifecycleService);
        when(shopItemLifecycleService.lockForUpdate(anyLong())).thenReturn(ShopItem.builder()
                .itemName("Rollback test item")
                .price(100)
                .itemType("EMOTICON")
                .targetId(1L)
                .build());
        when(imageLimitPolicy.getCurrentLimit()).thenReturn(20);
        when(userWritableResolver.resolve(anyLong())).thenReturn(null);

        doAnswer(invocation -> {
            Long fileId = invocation.getArgument(0);
            File file = fileRepository.findById(fileId).orElseThrow();
            file.markDeletionPending(LocalDateTime.now());
            fileRepository.flush();
            return true;
        }).when(fileService).deleteFileWithStorageIfAssociated(anyLong(), anyLong(), anyString());

        doAnswer(invocation -> {
            @SuppressWarnings("unchecked")
            List<Long> fileIds = invocation.getArgument(0);
            Long relatedId = invocation.getArgument(2);
            String relatedType = invocation.getArgument(3);
            for (Long fileId : fileIds) {
                File file = fileRepository.findById(fileId).orElseThrow();
                file.updateRelatedInfo(relatedId, relatedType);
            }
            fileRepository.flush();
            return fileIds.stream().map(FileUrlResolver::resolve).toList();
        }).when(fileService).associateFilesWithEntity(
                anyList(), anyLong(), anyLong(), anyString(), anyInt());
    }

    @Test
    @DisplayName("배치 수정의 마지막 메타데이터 검증 실패 시 이미지와 파일 상태를 모두 롤백한다")
    void updateEmoticon_blankNameAfterFileChanges_rollsBackWholeTransaction() {
        SeedData seed = testDataService.seed();
        EmoticonUpdateRequest request = EmoticonUpdateRequest.builder()
                .name("   ")
                .deleteImageIds(List.of(seed.oldImageId()))
                .addImageFileIds(List.of(seed.newFileId()))
                .build();

        assertThatThrownBy(() -> updater.update(seed.userId(), seed.emoticonId(), request))
                .isInstanceOf(BusinessException.class)
                .hasFieldOrPropertyWithValue("errorCode", ErrorCode.VALIDATION_ERROR);

        EmoticonMaster persistedMaster = emoticonMasterRepository.findByIdWithImages(seed.emoticonId())
                .orElseThrow();
        assertThat(persistedMaster.getName()).isEqualTo("원래 이름");
        assertThat(persistedMaster.getImages())
                .extracting(EmoticonImage::getImageId)
                .containsExactly(seed.oldImageId());
        assertThat(emoticonImageRepository.findById(seed.oldImageId())).isPresent();

        File oldFile = fileRepository.findById(seed.oldFileId()).orElseThrow();
        assertThat(oldFile.getStorageStatus()).isEqualTo(FileStorageStatus.ACTIVE);
        assertThat(oldFile.getRelatedId()).isEqualTo(seed.emoticonId());
        assertThat(oldFile.getRelatedType()).isEqualTo(EMOTICON_IMAGE_TYPE);
        assertThat(oldFile.getDeleteRequestedAt()).isNull();

        File newFile = fileRepository.findById(seed.newFileId()).orElseThrow();
        assertThat(newFile.getStorageStatus()).isEqualTo(FileStorageStatus.ACTIVE);
        assertThat(newFile.getRelatedId()).isNull();
        assertThat(newFile.getRelatedType()).isNull();
    }

    @Test
    @DisplayName("상품 생성 실패 시 이모티콘 생성도 함께 롤백한다")
    void createEmoticon_shopItemFailure_rollsBackMaster() {
        User user = userRepository.save(User.builder()
                .loginId("emoticon-create-rollback")
                .email("emoticon-create-rollback@test.com")
                .password("password")
                .displayName("Create Rollback")
                .build());
        when(userWritableResolver.resolve(user.getUserId())).thenReturn(user);
        doThrow(new DataIntegrityViolationException("shop item save failed"))
                .when(shopItemLifecycleService).createFor(any(EmoticonMaster.class));
        long beforeCount = emoticonMasterRepository.count();

        assertThatThrownBy(() -> updater.create(
                user.getUserId(),
                EmoticonCreateRequest.builder().name("롤백 상품").build()))
                .isInstanceOf(DataIntegrityViolationException.class);

        assertThat(emoticonMasterRepository.count()).isEqualTo(beforeCount);
    }

    @Test
    @DisplayName("상품 메타데이터 동기화 실패 시 이모티콘 수정도 함께 롤백한다")
    void updateEmoticon_shopItemFailure_rollsBackMaster() {
        SeedData seed = testDataService.seed();
        doThrow(new DataIntegrityViolationException("shop item update failed"))
                .when(shopItemLifecycleService).updatePresentation(any(ShopItem.class), any(EmoticonMaster.class));

        assertThatThrownBy(() -> updater.update(
                seed.userId(),
                seed.emoticonId(),
                EmoticonUpdateRequest.builder().name("변경 이름").build()))
                .isInstanceOf(DataIntegrityViolationException.class);

        EmoticonMaster persistedMaster = emoticonMasterRepository.findById(seed.emoticonId()).orElseThrow();
        assertThat(persistedMaster.getName()).isEqualTo("원래 이름");
    }

    private record SeedData(
            Long userId,
            Long emoticonId,
            Long oldImageId,
            Long oldFileId,
            Long newFileId) {
    }

    static class TransactionalEmoticonUpdater {

        private final EmoticonCommandService commandService;

        TransactionalEmoticonUpdater(EmoticonCommandService commandService) {
            this.commandService = commandService;
        }

        @Transactional
        void update(Long userId, Long emoticonId, EmoticonUpdateRequest request) {
            commandService.updateEmoticon(userId, emoticonId, request);
        }

        @Transactional
        void create(Long userId, EmoticonCreateRequest request) {
            commandService.createEmoticon(userId, request);
        }
    }

    static class TestDataService {

        private static final AtomicLong SEQUENCE = new AtomicLong();

        private final UserRepository userRepository;
        private final EmoticonMasterRepository emoticonMasterRepository;
        private final FileRepository fileRepository;

        TestDataService(
                UserRepository userRepository,
                EmoticonMasterRepository emoticonMasterRepository,
                FileRepository fileRepository) {
            this.userRepository = userRepository;
            this.emoticonMasterRepository = emoticonMasterRepository;
            this.fileRepository = fileRepository;
        }

        @Transactional
        SeedData seed() {
            long suffix = SEQUENCE.incrementAndGet();
            User user = userRepository.save(User.builder()
                    .loginId("emoticon-rollback-user-" + suffix)
                    .email("emoticon-rollback-" + suffix + "@test.com")
                    .password("password")
                    .displayName("Rollback User")
                    .build());
            EmoticonMaster master = emoticonMasterRepository.save(EmoticonMaster.builder()
                    .name("원래 이름")
                    .creator(user)
                    .tags(List.of("rollback"))
                    .build());
            File oldFile = fileRepository.save(File.builder()
                    .filePath("emoticons/old.png")
                    .originalName("old.png")
                    .fileSize(10L)
                    .mimeType("image/png")
                    .uploader(user)
                    .relatedId(master.getEmoticonId())
                    .relatedType(EMOTICON_IMAGE_TYPE)
                    .build());
            File newFile = fileRepository.save(File.builder()
                    .filePath("emoticons/new.png")
                    .originalName("new.png")
                    .fileSize(20L)
                    .mimeType("image/png")
                    .uploader(user)
                    .build());
            EmoticonImage oldImage = EmoticonImage.builder()
                    .imageUrl(FileUrlResolver.resolve(oldFile.getFileId()))
                    .sortOrder(0)
                    .build();
            master.addImage(oldImage);
            emoticonMasterRepository.flush();

            return new SeedData(
                    user.getUserId(),
                    master.getEmoticonId(),
                    oldImage.getImageId(),
                    oldFile.getFileId(),
                    newFile.getFileId());
        }
    }

    @TestConfiguration
    static class TestConfig {

        @Bean
        FileService fileService() {
            return mock(FileService.class);
        }

        @Bean
        UserWritableResolver userWritableResolver() {
            return mock(UserWritableResolver.class);
        }

        @Bean
        EmoticonImageLimitPolicy emoticonImageLimitPolicy() {
            return mock(EmoticonImageLimitPolicy.class);
        }

        @Bean
        EmoticonDeletePolicy emoticonDeletePolicy() {
            return mock(EmoticonDeletePolicy.class);
        }

        @Bean
        EmoticonShopItemLifecycleService emoticonShopItemLifecycleService() {
            return mock(EmoticonShopItemLifecycleService.class);
        }

        @Bean
        EmoticonAttachmentHelper emoticonAttachmentHelper(FileService fileService) {
            return new EmoticonAttachmentHelper(fileService);
        }

        @Bean
        EmoticonCommandService emoticonCommandService(
                EmoticonMasterRepository emoticonMasterRepository,
                UserWritableResolver userWritableResolver,
                EmoticonAttachmentHelper attachmentHelper,
                EmoticonDeletePolicy deletePolicy,
                EmoticonImageLimitPolicy imageLimitPolicy,
                EmoticonShopItemLifecycleService shopItemLifecycleService) {
            return new EmoticonCommandService(
                    emoticonMasterRepository,
                    userWritableResolver,
                    attachmentHelper,
                    deletePolicy,
                    imageLimitPolicy,
                    shopItemLifecycleService,
                    "EMOTICON_THUMBNAIL",
                    EMOTICON_IMAGE_TYPE);
        }

        @Bean
        TransactionalEmoticonUpdater transactionalEmoticonUpdater(EmoticonCommandService commandService) {
            return new TransactionalEmoticonUpdater(commandService);
        }

        @Bean
        TestDataService testDataService(
                UserRepository userRepository,
                EmoticonMasterRepository emoticonMasterRepository,
                FileRepository fileRepository) {
            return new TestDataService(userRepository, emoticonMasterRepository, fileRepository);
        }
    }
}
